import Head from "next/head";
import { ArrowRight, MessageSquare, Shield, Zap, Users } from 'lucide-react';
import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    // const token = localStorage.getItem('token');
    
    // if (!token) {
    //   router.push('/login');
    // }
  }, [router]);

  return (
    <>
		<Head>
			<title>Home | Voxby</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
			{/* Hero Section */}
			<section className="pt-20 pb-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
					<div className="text-center">
						<h1 className="text-5xl font-bold text-gray-900 mb-6 bg-gradient-to-r from-purple-600 to-indigo-600 bg-clip-text text-transparent">
							Welcome to Voxby
						</h1>
						<p className="text-xl text-gray-600 max-w-2xl mx-auto">
							Transform your voice recordings into accurate, actionable text with our advanced AI-powered transcription service.
						</p>
					</div>
			</section>

			{/* What is Voxby Section */}
			<section className="py-16 bg-gradient-to-r from-indigo-50 to-purple-50">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
					<h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">What is Voxby?</h2>
					<div className="grid md:grid-cols-2 gap-12 items-center">
						<div>
							<p className="text-lg text-gray-700 leading-relaxed">
								Voxby is a state-of-the-art voice transcription platform that combines cutting-edge AI technology with user-friendly design. Our service helps professionals, students, and businesses convert spoken words into accurate written text quickly and efficiently.
							</p>
						</div>
						<div className="bg-white p-6 rounded-2xl shadow-xl">
							<div className="grid grid-cols-2 gap-4">
								<div className="p-4 text-center">
									<div className="text-indigo-600 text-2xl font-bold">99%</div>
									<div className="text-gray-600">Accuracy</div>
								</div>
								<div className="p-4 text-center">
									<div className="text-indigo-600 text-2xl font-bold">40+</div>
									<div className="text-gray-600">Languages</div>
								</div>
								<div className="p-4 text-center">
									<div className="text-indigo-600 text-2xl font-bold">24/7</div>
									<div className="text-gray-600">Support</div>
								</div>
								<div className="p-4 text-center">
									<div className="text-indigo-600 text-2xl font-bold">1M+</div>
									<div className="text-gray-600">Users</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* How to Use Section */}
			<section className="py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
				<h2 className="text-3xl font-bold text-gray-900 mb-12 text-center">How to Use Voxby?</h2>
				<div className="grid md:grid-cols-3 gap-8">
					<div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
						<div className="text-indigo-600 mb-4">
							<MessageSquare size={32} />
						</div>
						<div>
							<h3 className="text-xl font-semibold mb-3">1. Upload Your Recording</h3>
							<p className="text-gray-600">Simply upload your audio or video file in any common format. We support MP3, WAV, MP4, and more.</p>
						</div>
					</div>
					<div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
						<div className="text-indigo-600 mb-4">
							<Zap size={32} />
						</div>
						<div>
							<h3 className="text-xl font-semibold mb-3">2. AI Processing</h3>
							<p className="text-gray-600">Our AI technology processes your file, converting speech to text with high accuracy and speed.</p>
						</div>
					</div>
					<div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
						<div className="text-indigo-600 mb-4">
							<ArrowRight size={32} />
						</div>
						<div>
							<h3 className="text-xl font-semibold mb-3">3. Get Your Transcript</h3>
							<p className="text-gray-600">Download your transcript in multiple formats including TXT, PDF, or Word document.</p>
						</div>
					</div>
				</div>
			</section>

			{/* Benefits Section */}
			<section className="py-16 bg-gradient-to-r from-purple-50 to-indigo-50">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
					<h2 className="text-3xl font-bold text-gray-900 mb-12 text-center">Why Choose Voxby?</h2>
					<div className="grid md:grid-cols-2 gap-8">
						<div className="bg-white p-6 rounded-xl shadow-lg">
							<div className="flex items-start space-x-4">
								<div className="text-indigo-600">
									<Shield size={24} />
								</div>
								<div>
									<h3 className="text-xl font-semibold mb-2">Security First</h3>
									<p className="text-gray-600">Your data is encrypted end-to-end, ensuring complete privacy and security of your content.</p>
								</div>
							</div>
						</div>
						<div className="bg-white p-6 rounded-xl shadow-lg">
							<div className="flex items-start space-x-4">
								<div className="text-indigo-600">
									<Users size={24} />
								</div>
								<div>
									<h3 className="text-xl font-semibold mb-2">Team Collaboration</h3>
									<p className="text-gray-600">Share transcripts with team members and collaborate in real-time with comments and edits.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>

			{/* CTA Section */}
			<section className="py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
				<div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl py-12 px-6 text-white">
					<h2 className="text-3xl font-bold mb-4">Ready to Get Started?</h2>
					<p className="text-xl mb-8 opacity-90">Experience the power of Voxby's AI transcription today.</p>
					<Link href="/login" className="inline-flex items-center gap-2 bg-white text-indigo-600 px-8 py-3 rounded-lg font-semibold hover:bg-opacity-90 transition-colors">
            Voxby Now <ArrowRight size={16} /></Link>
				</div>
			</section>
   		</div>
    </>
  );
}